---
- name: test vars
  hosts: localhost
  gather_facts: no

  vars:
    support_os:
      rhel:
        include: yes
        count: 1
        instance_type: "t2.medium"

  # Yes to RHEL or no
  # RHEL COUNT <integer>

  tasks:
    - debug:
        msg: "{{ tower_os_rhel }} and {{tower_rhel_count }}"

